name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: Jimver/cuda-toolkit@v0.2.19
      id: cuda-toolkit
      with:
        cuda: '9.2.148'
    
    - name: compile or somthing idk
      run: |
       cd /usr/local/cuda-9.2/lib64
       ls 

       
