name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: Jimver/cuda-toolkit@v0.2.19
      id: cuda-toolkit
      with:
        cuda: '9.2'
    
    - name: compile or somthing idk
      run: |
       cd binary
       curl http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64/cuda-repo-ubuntu1710_9.2.148-1_amd64.deb -O -J -L
       sudo dpkg -i cuda-repo-ubuntu1710_9.2.148-1_amd64.deb
       sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1710/x86_64/7fa2af80.pub
       sudo apt-get update
       sudo apt-get install cuda
       export PATH=/usr/local/cuda-9.2/bin:$PATH.
       cd /usr/local/cuda-9.2/lib64
       ls 

       
