name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: compile or somthing idk
      run: |
       cd binary
       curl https://github.com/premake/premake-core/releases/download/v5.0.0-beta3/premake-5.0.0-beta3-linux.tar.gz -O -J -L
       tar -xvzf premake-5.0.0-beta3-linux.tar.gz
       sudo chmod +x ./premake5
       ./premake5 gmake
       make config=release_x86_64

    - name: Upload artifact
      uses: actions/upload-artifact@v4.3.1
      with:
          name: gmcl_gwater2_linux64.dll
          path: binary/x86_64/Release/gmcl_gwater2_linux64.dll
          if-no-files-found: error
    
