name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
steps:
- name: Setup Premake
  uses: premake/setup-premake@v1
  with:
    version: 5.0.0-alpha16
- name: Generate project with tests
  run: premake5 gmake2
- name: Build tests
  run: make config=release tests
- name: Run tests
  run: |
    cd build/tests
    ./test_binary
