name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: do the shits
      run: |
        cd binary
        curl -LO https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip     
        dir
        7z x premake-5.0.0-beta2-windows.zip
        git clone https://github.com/danielga/garrysmod_common.git --recursive -b x86-64-support-sourcesdk
        premake5.exe vs2022
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build app for release
      run: msbuild gmcl_gwater2.vcxproj -t:rebuild -verbosity:diag -property:Configuration=Release
